---
output: html_document
---

## Exercise 5.7

__In Sections 5.3.2 and 5.3.3, we saw that the `cv.glm()` function can be used in order to compute the LOOCV test error estimate. Alternatively, one could compute those quantities using just the `glm()` and `predict.glm()` functions, and a for loop. You will now take this approach in order to compute the LOOCV error for a simple logistic regression model on the Weekly data set. Recall that in the context of classification problems, the LOOCV error is given in (5.4).__

a. __Fit a logistic regression model that predicts Direction using Lag1 and Lag2.__

<!-- enter your solution here -->

b. __Fit a logistic regression model that predicts Direction using Lag1 and Lag2 using all but the first observation.__

<!-- enter your solution here -->

c. __Use the model from (b) to predict the direction of the first observation. You can do this by predicting that the first observation will go up if `P(Direction="Up"|Lag1, Lag2) > 0.5`. Was this observation correctly classified?__

<!-- enter your solution here -->

d. __Write a for loop from `i = 1` to `i = n`, where n is the number of observations in the data set, that performs each of the following steps:__

    i. __Fit a logistic regression model using all but the $i^{th}$ observation to predict Direction using Lag1 and Lag2.__

    ii. __Compute the posterior probability of the market moving up for the ith observation.__

    iii. __Use the posterior probability for the ith observation in order to predict whether or not the market moves up.__

    iv. __Determine whether or not an error was made in predicting the direction for the $i^{th}$ observation. If an error was made, then indicate this as a 1, and otherwise indicate it as a 0.__

<!-- enter your solution here -->

e. __Take the average of the n numbers obtained in (d)iv in order to obtain the LOOCV estimate for the test error. Comment on the results.__

<!-- enter your solution here -->
